# Generated by Django 5.2.1 on 2025-08-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controller', '0002_alter_cliente_options_alter_motorista_options_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='app_controller_usuario_set', related_query_name='app_controller_usuario', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='app_controller_usuario_set', related_query_name='app_controller_usuario', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(fields=('username',), name='unique_username'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email'),
        ),
    ]
