# Generated by Django 5.2.1 on 2025-08-23 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controller', '0003_alter_usuario_groups_alter_usuario_user_permissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoVale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='vales/documentos/')),
                ('nome_original', models.CharField(max_length=255)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app_controller.valepallet')),
            ],
            options={
                'verbose_name': 'Documento do Vale',
                'verbose_name_plural': 'Documentos dos Vales',
                'ordering': ['-data_upload'],
            },
        ),
    ]
