# Generated by Django 5.2.6 on 2025-09-06 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_controller', '0004_documentovale'),
        ('app_controller', '0007_alter_usuario_groups_alter_usuario_telefone_and_more'),
    ]

    operations = [
    ]
