# Generated by Django 5.2.6 on 2025-09-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controller', '0008_merge_20250906_1815'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='usuario',
            name='unique_username',
            constraint=models.UniqueConstraint(fields=('username',), name='unique_username'),
        ),
        migrations.AlterConstraint(
            model_name='usuario',
            name='unique_email',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email'),
        ),
    ]
